# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', models.CharField(max_length=200)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooster.Chauffeur')),
            ],
        ),
    ]
