# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0007_chauffeur_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='user',
        ),
    ]
