# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0009_chauffeur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dienst',
            name='percentage',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='stddienst',
            name='percentage',
            field=models.FloatField(default=1),
        ),
    ]
