# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0010_auto_20170214_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dienst',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='stddienst',
            name='percentage',
        ),
    ]
