# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0011_auto_20170215_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='dienst',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
