# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0016_dienst_overname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='phone',
            field=models.CharField(default='06-12345678', max_length=20),
            preserve_default=False,
        ),
    ]
